import os

files = [
    "src/index.css",
    "tailwind.config.js",
    "src/main.tsx",
    "src/App.tsx",
    "src/components/Sidebar.tsx",
    "src/components/TopBar.tsx",
    "src/components/MainCanvas.tsx",
    "src/components/DisclaimerModal.tsx",
    "src/components/OmniSearchBar.tsx",
    "src/pages/CommandCenterPage.tsx",
    "src/pages/PlayerProfilePage.tsx",
    "src/pages/MatchupEnginePage.tsx",
    "src/pages/MatchupLabPage.tsx",
    "src/pages/TeamCentralPage.tsx",
    "src/pages/SettingsPage.tsx",
    "src/pages/PulsePage.tsx",
    "src/pages/VanguardControlRoom.tsx",
    "src/pages/BoxScoresPage.tsx",
    "src/pages/InjuryAdmin.tsx",
    "src/pages/AboutPage.tsx",
    "src/components/PlayByPlay/PlayByPlay.css",
    "src/components/aegis/MatchupWarRoom.css",
    "src/components/common/ErrorBoundaryWithFallback.css",
    "src/components/common/FreshnessHalo.css",
    "src/components/common/NextDayDriftToast.css",
    "src/components/common/WhyTooltip.css",
    "src/components/matchup/FrictionHeatMap.css",
    "src/components/matchup/ProgressiveLoadingSkeleton.css",
    "src/components/matchup/UsageVacuumToggle.css",
    "src/pages/MatchupLabPage.css",
    "src/components/common/MetricCard.tsx",
    "src/components/common/StatusLed.tsx",
    "src/components/common/Sparkline.tsx",
    "src/components/common/ConfidenceRing.tsx",
    "src/components/common/Modal.tsx",
    "src/components/common/ToastContainer.tsx",
    "src/components/common/WhyTooltip.tsx",
    "src/components/common/CascadingSelector.tsx",
    "src/components/common/ConnectionStatus.tsx",
    "src/components/common/DataProvenanceBadge.tsx",
    "src/components/common/DefenderImpactTooltip.tsx",
    "src/components/common/FatigueBreakdownChip.tsx",
    "src/components/common/ResponsiveContainer.tsx",
    "src/components/common/ResponsiveGrid.tsx",
    "src/components/common/SectionErrorBoundary.tsx",
    "src/components/common/ConfirmDialog.tsx",
    "src/components/common/ErrorBoundaryWithFallback.tsx",
    "src/components/profile/HeroSection.tsx",
    "src/components/profile/NarrativeBlock.tsx",
    "src/components/profile/ProbabilityGauge.tsx",
    "src/components/profile/EnrichedPlayerCard.tsx",
    "src/components/matchup/MatchupRadar.tsx",
    "src/components/matchup/FrictionHeatMap.tsx",
    "src/components/matchup/InsightBanner.tsx",
    "src/components/matchup/UsageVacuumToggle.tsx",
    "src/components/matchup/ProgressiveLoadingSkeleton.tsx",
    "src/components/aegis/MatchupWarRoom.tsx",
    "src/components/aegis/ProjectionMatrix.tsx",
    "src/components/aegis/PlayTypeEfficiency.tsx",
    "src/components/aegis/VertexMatchupCard.tsx",
    "src/components/player/GameLogsViewer.tsx",
    "src/components/player/H2HHistoryPanel.tsx",
    "src/components/player/PlayerShotChart.tsx",
    "src/components/vanguard/VanguardHealthWidget.tsx",
    "src/components/vanguard/VanguardControlRoom.tsx",
    "src/components/vanguard/VanguardArchivesViewer.tsx",
    "src/components/vanguard/VanguardLearningExport.tsx",
    "src/components/vanguard/VaccinePanel.tsx",
    "src/components/PlayByPlay/PlayByPlayFeed.tsx",
    "src/components/PlayByPlay/PlayItem.tsx",
    "src/components/PlayByPlay/GameScoreHeader.tsx",
    "src/components/PlayByPlay/LiveGameSelector.tsx",
    "src/components/PlayByPlay/InteractiveShotChart.tsx",
    "src/components/PlayByPlay/ConnectionStatus.tsx",
    "src/components/dashboard/BoxScoreViewer.tsx",
    "src/components/settings/HealthDepsPanel.tsx",
    "src/components/ui/alert.tsx",
    "src/components/ui/button.tsx",
    "src/components/ui/card.tsx",
    "src/components/ui/input.tsx",
    "src/components/ui/label.tsx",
    "src/components/ui/select.tsx",
    "src/components/ui/index.tsx"
]

with open('all_frontend_code.txt', 'w', encoding='utf-8') as out:
    for fpath in files:
        out.write(f"\n\n{'='*80}\n")
        out.write(f"FILE: {fpath}\n")
        out.write(f"{'='*80}\n\n")
        try:
            with open(fpath, 'r', encoding='utf-8') as f:
                out.write(f.read())
        except Exception as e:
            out.write(f"ERROR READING {fpath}: {e}\n")

print("Done generating all_frontend_code.txt")
