import React, { useEffect, useState, useCallback } from 'react';
import { UserPlus, Activity, ShieldCheck, XCircle, FileCode, CheckCircle2 } from 'lucide-react';
import { ApiContract } from '../../api/client';
import { SectionErrorBoundary } from '../common/SectionErrorBoundary';

interface VaccineDefinition {
    id: string;
    name: string;
    description: string;
    status: 'ACTIVE' | 'DRAFT' | 'ERROR';
    deployment_date: string;
    target_pattern: string;
    hit_count: number;
}

export function VaccinePanelContent() {
    const [loading, setLoading] = useState(false);
    const [vaccines, setVaccines] = useState<VaccineDefinition[]>([]);

    const loadVaccines = useCallback(async () => {
        setLoading(true);
        try {
            const res = await ApiContract.execute<{ vaccines: VaccineDefinition[] }>(null, {
                path: 'vanguard/admin/vaccines'
            });
            setVaccines(res.data?.vaccines || []);
        } catch (e) {
            console.error("Failed to load Vanguard vaccines", e);
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        loadVaccines();
    }, [loadVaccines]);

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4 border-b border-slate-700/50 pb-5">
                <div>
                    <h2 className="text-white font-black text-xl flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center">
                            <ShieldCheck className="w-5 h-5 text-indigo-400" />
                        </div>
                        Vaccine Definitions
                    </h2>
                    <p className="text-sm text-slate-400 mt-1 max-w-2xl leading-relaxed">
                        Automatic code-level remediations applied by Vanguard during incident recovery.
                        These are generated by the Surgeon subsystem and applied ahead-of-time (AOT).
                    </p>
                </div>

                <button
                    onClick={loadVaccines}
                    disabled={loading}
                    className="flex items-center gap-2 px-4 py-2 border border-slate-600 hover:bg-slate-800 disabled:opacity-50 text-slate-300 rounded-lg text-sm font-bold transition-colors whitespace-nowrap"
                >
                    <Activity className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                    Refresh Policy
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {/* Always show the core default vaccine that protects from the shadow paradox */}
                <div className="bg-indigo-950/20 border border-indigo-500/30 rounded-xl p-5 shadow-[0_0_20px_rgba(99,102,241,0.05)] relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-bl-full -mr-8 -mt-8 pointer-events-none" />

                    <div className="flex justify-between items-start mb-4">
                        <div className="text-indigo-400 font-mono text-xs tracking-wider bg-black/40 px-2.5 py-1 rounded inline-block shadow-sm">
                            VACCINE-001 (CORE)
                        </div>
                        <CheckCircle2 className="w-5 h-5 text-emerald-400 shadow-sm" />
                    </div>

                    <h3 className="text-slate-200 font-bold mb-2">Shadow Service Protection</h3>
                    <p className="text-slate-400 text-sm leading-relaxed mb-4 min-h-[40px]">
                        Defensive wrapper for multi-container deployments where obsolete routes throw UnboundLocalError during initialization.
                    </p>

                    <div className="grid grid-cols-2 gap-3 border-t border-slate-700/50 pt-4 mt-auto">
                        <div>
                            <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Target</div>
                            <div className="text-xs text-slate-300 font-mono flex items-center gap-1">
                                <FileCode className="w-3 h-3 text-emerald-400" /> main.py
                            </div>
                        </div>
                        <div>
                            <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Total Blocks</div>
                            <div className="text-sm text-white font-black">24,401</div>
                        </div>
                    </div>
                </div>

                {/* Map dynamic ones */}
                {loading && vaccines.length === 0 ? (
                    <div className="col-span-full py-16 text-center text-slate-500 flex flex-col items-center border border-dashed border-slate-700/50 rounded-xl">
                        <Activity className="w-8 h-8 mb-3 animate-spin opacity-50 text-indigo-400" />
                        Scanning remote definitions...
                    </div>
                ) : (
                    vaccines.map((vac) => (
                        <div key={vac.id} className="bg-slate-800/40 border border-slate-700/50 rounded-xl p-5 shadow-sm hover:border-slate-500/50 transition-colors flex flex-col group relative overflow-hidden">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-slate-500/5 rounded-bl-full -mr-8 -mt-8 pointer-events-none" />

                            <div className="flex justify-between items-start mb-4">
                                <div className="text-slate-400 font-mono text-xs tracking-wider bg-black/40 px-2.5 py-1 rounded inline-block shadow-sm">
                                    {vac.id}
                                </div>
                                {vac.status === 'ACTIVE' ? (
                                    <CheckCircle2 className="w-5 h-5 text-emerald-400 shadow-sm" />
                                ) : vac.status === 'DRAFT' ? (
                                    <ShieldCheck className="w-5 h-5 text-amber-400 shadow-sm" />
                                ) : (
                                    <XCircle className="w-5 h-5 text-red-400 shadow-sm" />
                                )}
                            </div>

                            <h3 className="text-slate-200 font-bold mb-2 break-words leading-tight">{vac.name}</h3>
                            <p className="text-slate-400 text-sm leading-relaxed mb-4 min-h-[40px]">
                                {vac.description}
                            </p>

                            <div className="grid grid-cols-2 gap-3 border-t border-slate-700/50 pt-4 mt-auto">
                                <div>
                                    <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Target</div>
                                    <div className="text-xs text-slate-300 font-mono flex items-center gap-1 overflow-hidden" title={vac.target_pattern}>
                                        <FileCode className="w-3 h-3 text-slate-400 flex-shrink-0" />
                                        <span className="truncate">{vac.target_pattern.split('/').pop() || vac.target_pattern}</span>
                                    </div>
                                </div>
                                <div>
                                    <div className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Total Blocks</div>
                                    <div className="text-sm text-white font-black">{vac.hit_count.toLocaleString()}</div>
                                </div>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}

export const VaccinePanel = () => (
    <SectionErrorBoundary fallbackMessage="Vaccine System Definitions offline">
        <VaccinePanelContent />
    </SectionErrorBoundary>
);
